version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/bigtest.js.org
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache
      - run: yarn install
      - save_cache:
          key: dependency-cache
          paths:
            - ~/.yarn
            - ~/.cache/yarn
            - vendor/bundle
      - run:
          name: Configure git
          command: |
            git config --global user.email "yesno@users.noreply.github.com"
            git config --global user.name "yesno"
            echo "machine github.com login yesno password $GITHUB_TOKEN" > ~/.netrc
      - run:
          name: Lint Project
          command: yarn lint
      - deploy:
          name: Deploy to Production
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              cd website && yarn install && GIT_USER=yesno yarn run publish-gh-pages
            fi
