version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
    deployment:
      website:
        branch: master
        commands:
          - git config --global user.email "SamKeathley@users.noreply.github.com"
          - git config --global user.name "SamKeathley"
          - echo "machine github.com login SamKeathley password $GITHUB_TOKEN" > ~/.netrc
          - cd website && npm install && GIT_USER=SamKeathley USE_SSH=true npm run publish-gh-pages
