references:
  defaults: &defaults
    working_directory: ~/bigtest.js.org
    docker:
      - image: circleci/ruby:2.4-node

  cache_key: &cache_key
    bigtest.js.org-v1-{{ .Branch }}-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}

  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/bigtest.js.org

  persist_workspace: &persist_workspace
      persist_to_workspace:
        root: ~/bigtest.js.org
        paths:
          - ./

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore cache
          key: *cache_key
      - run:
          name: Install bundle dependencies
          command: bundle
      - run:
          name: Install package dependencies
          command: yarn
      - save_cache:
          name: Save cache
          key: *cache_key
          paths:
            - node_modules
            - vendor/bundle
      - *persist_workspace

  build:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Build
          command: rake build
      - *persist_workspace

  deploy:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Publish to gh-pages
          command: rake publish

workflows:
  version: 2
  default:
    jobs:
      - install
      - build:
          requires:
            - install
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
